services:
  workspace:
    build: .
    volumes:
      - .:/home/user/workspace 
    working_dir: /home/user/workspace
    ports:
      - "8000:8000" 
      - "5173:5173" 
    environment:
      UID: 1000
      GID: 1000
    tty: true 
